# permissions for end users to edit pipelinerunstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pipelinerunstatus-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tkn-github-status
    app.kubernetes.io/part-of: tkn-github-status
    app.kubernetes.io/managed-by: kustomize
  name: pipelinerunstatus-editor-role
rules:
- apiGroups:
  - status.kcloutie.com
  resources:
  - pipelinerunstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - status.kcloutie.com
  resources:
  - pipelinerunstatuses/status
  verbs:
  - get
